cloud         model.cloud    #  cloud defined on a Cartesian grid
alpha          -0.8
nray           1024
distance       140.0           #  cloud distance [pc]
angle          430.0             #  model cell size  [arcsec]
molecule       hcn@hfs.dat    #  name of the Lamda file
density        1.0          #  scaling of densities in the cloud file
temperature    1.0             #  scaling of Tkin values in the cloud file
fraction       1.0         #  scaling o the fraction abundances
velocity       1.0             #  scaling of the velocity
sigma          1.0             #  scaling o the microturbulence
isotropic      2.73            #  Tbg for the background radiation field
levels         19              #  number of energy levels in the calculations
uppermost      19               #  uppermost level tracked for convergence
iterations     80               #  number of iterations
nside          2               #  NSIDE parameter determining the number of rays (angles)
direction      90 0.001        #  theta, phi [deg] for the direction towards the observer
points        16 16         #  number of pixels in the output maps
grid           3.0             #  map pixel size [arcsec]
spectra       2 0 1 0 3 0 7 5 9 6 7 4 8 5 9 5 9 4   #  spectra written for transitions == upper lower (pair of integers)
transitions   2 0 1 0 3 0 7 5 9 6 7 4 8 5 9 5 9 4   #  Tex saved for transitions (upper and lower levels of each transition)
bandwidth      26.0             #  bandwidth in the calculations [km/s]
channels       1181           #  (36) number of velocity channels
prefix        HCN     #  prefix for output files
#load        HCN.save       #  load level populations
#save         HCN.save       #  save level populations
stop          -1.0             #  stop if level-populations change below a threshold
gpu            0               #  gpu>0 => use the first available gpu
overlap       hcn_overlap.dat
